In [10]:
#Hacer las importaciones necesarias para abrir un archivo de tipo "csv" en Pandas.

import pandas as pd

In [23]:
#Abrir el archivo, creando un Dataframe. Aseguraros de que no incluye la columna "Unnamed: 0".

df_videogames = pd.read_csv("videogames.csv")

df_videogames = pd.read_csv("videogames.csv", index_col = 0)

df_videogames

,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False
4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,True,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20798,"Enjoy Your Power, Enjoy Your Choice",https://www.imdb.com/title/tt3845606/?ref_=adv...,2014.0,NaN,NaN,NaN,Add a Plot,False,False,False,False,False,False,False,False,True
20799,RedSun2020,https://www.imdb.com/title/tt0790739/?ref_=adv...,2004.0,NaN,NaN,NaN,Joseph gets kidnapped and it's the player's jo...,False,False,False,False,False,False,False,False,True
20800,Shutter,https://www.imdb.com/title/tt5119948/?ref_=adv...,2015.0,NaN,NaN,NaN,A tech support man who uses a drone to investi...,False,False,False,False,False,False,False,False,True
20801,The Music Machine,https://www.imdb.com/title/tt5142082/?ref_=adv...,2015.0,NaN,NaN,NaN,A young teenage girl and the ghost of a dead m...,False,False,False,False,False,False,False,False,True
20802,Cryptic,https://www.imdb.com/title/tt10964974/?ref_=ad...,2020.0,NaN,NaN,NaN,Kidnapped by an insane man and dragged into a ...,False,False,False,False,False,False,False,False,True

In [ ]:
#Una vez creado el Dataframe, muestra las 10 primeras filas.

df_videogames.head(11)

In [ ]:
#Â¿CÃºal es el Ãºltimo Ã­ndice que tenemos en el Dataframe?

df_videogames.info()

In [14]:
#Mostrar 15 filas aleatorias.

df_videogames.sample(15)

,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
14562,Getsu FÃ»ma Den,https://www.imdb.com/title/tt9649318/?ref_=adv...,1987.0,NaN,NaN,NaN,Add a Plot,False,True,False,False,False,False,False,False,False
20780,Monitor: The Game,https://www.imdb.com/title/tt7419456/?ref_=adv...,2017.0,NaN,NaN,NaN,Add a Plot,False,False,False,False,False,False,False,False,True
10875,Rune Factory 4,https://www.imdb.com/title/tt4203732/?ref_=adv...,2012.0,E10+,8.1,36,Add a Plot,False,True,False,False,False,False,False,False,False
3645,Rygar: The Legendary Adventure,https://www.imdb.com/title/tt0360942/?ref_=adv...,2002.0,T,7.3,44,Princess Harmonia has been kidnapped by the Ti...,True,True,False,False,False,True,False,False,False
8407,Megaforce,https://www.imdb.com/title/tt2310115/?ref_=adv...,1984.0,NaN,5.2,23,Add a Plot,True,False,False,False,False,False,False,True,False
1373,102 Dalmatians: Puppies to the Rescue,https://www.imdb.com/title/tt0272423/?ref_=adv...,2000.0,E,6.7,190,Oddball and Domino are two young Dalmatian pup...,True,False,True,False,True,False,False,False,False
13169,Stargate Adventure,https://www.imdb.com/title/tt8057218/?ref_=adv...,2005.0,NaN,NaN,NaN,Fan made adventure game based on the Stargate ...,False,True,False,False,False,False,False,True,False
15358,Job Simulator: The 2050 Archives,https://www.imdb.com/title/tt7571518/?ref_=adv...,2016.0,E10+,7.5,94,"In the year 2050, where robots are used for al...",False,False,True,False,False,False,False,False,False
6562,Napoleon,https://www.imdb.com/title/tt9480260/?ref_=adv...,2001.0,NaN,NaN,NaN,Add a Plot,True,False,False,False,False,False,False,False,False
11718,Days of Oblivion,https://www.imdb.com/title/tt5586546/?ref_=adv...,1996.0,M,NaN,NaN,Tongue in cheek FMV adventure game with some m...,False,True,False,False,False,False,False,True,False
14896,Panzer Dragoon Orta,https://www.imdb.com/title/tt0349934/?ref_=adv...,2002.0,T,7.8,94,"Having lived imprisoned her entire life, a you...",True,True,False,False,False,False,False,False,False
13871,Qui Domi,https://www.imdb.com/title/tt5986062/?ref_=adv...,2017.0,NaN,NaN,NaN,Annabelle was wandering about in her own room ...,False,True,False,False,False,True,False,False,False
16543,Who Wants to Be King of the Jungle,https://www.imdb.com/title/tt3231690/?ref_=adv...,2004.0,NaN,4.2,10,Add a Plot,False,False,False,False,True,False,False,False,False
2832,Cowboy Bebop: Serenade of Reminiscence,https://www.imdb.com/title/tt0965597/?ref_=adv...,2005.0,Not Rated,8.2,50,The game follows an original story set in the ...,True,True,False,True,False,False,False,False,False
10839,Frogger,https://www.imdb.com/title/tt0294587/?ref_=adv...,1997.0,E,6.9,150,"In this remake of the original of 1981, Frogge...",False,True,False,False,True,False,False,False,False

In [29]:
#Crea una lista con el nombre de las columnas.
df_videogames.columns.tolist()

['name',
 'url',
 'year',
 'certificate',
 'rating',
 'votes',
 'plot',
 'Action',
 'Adventure',
 'Comedy',
 'Crime',
 'Family',
 'Fantasy',
 'Mystery',
 'Sci-Fi',
 'Thriller']

In [16]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\profile1\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in c:\users\profile1\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: C:\Users\profile1\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [30]:
#Guardar el Dataframe en formato Excel y despuÃ©s crear un Dataframe con el Excel. Â¿EL Dataframe es similar al que tenÃ­ais antes?
df_videogames.to_excel("videogames.xlsx")

In [32]:
#Muestra la "info" del Dataframe.
df_videogames_excel = pd.read_excel("videogames.xlsx", index_col = 0)

df_videogames_excel

,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False
4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,True,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20798,"Enjoy Your Power, Enjoy Your Choice",https://www.imdb.com/title/tt3845606/?ref_=adv...,2014.0,NaN,NaN,NaN,Add a Plot,False,False,False,False,False,False,False,False,True
20799,RedSun2020,https://www.imdb.com/title/tt0790739/?ref_=adv...,2004.0,NaN,NaN,NaN,Joseph gets kidnapped and it's the player's jo...,False,False,False,False,False,False,False,False,True
20800,Shutter,https://www.imdb.com/title/tt5119948/?ref_=adv...,2015.0,NaN,NaN,NaN,A tech support man who uses a drone to investi...,False,False,False,False,False,False,False,False,True
20801,The Music Machine,https://www.imdb.com/title/tt5142082/?ref_=adv...,2015.0,NaN,NaN,NaN,A young teenage girl and the ghost of a dead m...,False,False,False,False,False,False,False,False,True
20802,Cryptic,https://www.imdb.com/title/tt10964974/?ref_=ad...,2020.0,NaN,NaN,NaN,Kidnapped by an insane man and dragged into a ...,False,False,False,False,False,False,False,False,True

In [ ]:
#Â¿Tiene nulos o duplicados?
#df_videogames_excel.isnull().sum()
df_videogames_excel.isna().sum()

In [59]:
df_videogames_excel.duplicated().sum()

1

In [55]:
#Obtener la descripciÃ³n del Dataframe, tanto de las columnas numÃ©ricas cÃ³mo de las de tipo "object". Explorar el resultado y sacar unas mÃ­nimas comclusiones sobre los datos que habÃ©is obtenido.
df_videogames_excel.describe(include="object")

,name,url,certificate,votes,plot
count,20803,20803,7903,11600,20803
unique,19714,20157,21,1905,11276
top,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,T,7,Add a Plot
freq,9,4,2474,318,8874

In [57]:
df_videogames_excel["name"].value_counts()

name
Spider-Man                        9
God of War                        6
Sonic the Hedgehog                6
Star Trek                         6
Resident Evil 2                   5
                                 ..
Elevator Action                   1
Nobuyuki Forces 4                 1
Cross Fire: king of gun battle    1
Duke: Nuclear Winter              1
Cryptic                           1
Name: count, Length: 19714, dtype: int64

In [22]:
#Finalmente, guarda el Dataframe en formato "csv" con un nombre diferente del original.
df_videogames_excel.to_csv("videogames.csv")